[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefer-offline --no-audit --production"
  VITE_BUILD_OPTIMIZE = "true"

# Production context
[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production" }

# Deploy preview context  
[context.deploy-preview]
  command = "npm run build"
  environment = { NODE_ENV = "preview" }

# Branch deploy context
[context.branch-deploy]
  command = "npm run build"
  environment = { NODE_ENV = "development" }

# Function optimization
[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@neondatabase/serverless",
    "jsonwebtoken",
    "jose",
    "cloudinary",
    "resend",
    "winston",
    "yargs",
    "yauzl",
    "ws"
  ]

# Cache optimization
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"