[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.19.4"
  NPM_FLAGS = "--prefer-offline --no-audit --production"
  VITE_BUILD_OPTIMIZE = "true"

# Production context
[context.production]
  command = "npm install && npm run build"
  environment = { NODE_ENV = "production" }

# Deploy preview context  
[context.deploy-preview]
  command = "npm install && npm run build"
  environment = { NODE_ENV = "preview" }

# Branch deploy context
[context.branch-deploy]
  command = "npm install && npm run build"
  environment = { NODE_ENV = "development" }

# Function optimization
[functions]
  node_bundler = "esbuild"
  # Ensure all dependencies are bundled
  external_node_modules = []

# Function-specific configurations
[functions."aimlApi"]
  timeout = 26   # Netlify max for normal functions
  memory = 1024

# Function dependencies are handled by top-level package.json

# Cache optimization
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Content Security Policy for dev server
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; frame-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self';"