
[build]
  command = "bash scripts/build-for-netlify.sh"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.19.4"
  NPM_FLAGS = "--prefer-offline --no-audit --force"
  VITE_BUILD_OPTIMIZE = "true"
  PRISMA_GENERATE_DATAPROXY = "false"
  PRISMA_CLIENT_ENGINE_TYPE = "library"

  PRISMA_CLI_QUERY_ENGINE_TYPE = "library"
  

# Production context
[context.production]
  command = "bash scripts/build-for-netlify.sh"
  environment = { NODE_ENV = "production" }

# Deploy preview context  
[context.deploy-preview]
  command = "bash scripts/build-for-netlify.sh"
  environment = { NODE_ENV = "preview" }

# Branch deploy context
[context.branch-deploy]
  command = "bash scripts/build-for-netlify.sh"
  environment = { NODE_ENV = "preview" }

# Function optimization
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]
  included_files = ["node_modules/.prisma/client/**", "prisma/schema.prisma"]

# Function-specific configurations
[functions."aimlApi"]
  timeout = 26   # Netlify max for normal functions
  memory = 1024

# Function dependencies are handled by top-level package.json

# Cache optimization
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Content Security Policy for dev server
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' data: https: blob:; font-src 'self' data:; connect-src 'self' https:; frame-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self';"