[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

[dev]
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
  # Allow Cloudinary + AIML API for images and media
  Content-Security-Policy = "default-src 'self'; img-src 'self' data: blob: https://res.cloudinary.com https://cdn.aimlapi.com; media-src 'self' blob: https://res.cloudinary.com https://cdn.aimlapi.com; connect-src 'self' https://api.cloudinary.com https://res.cloudinary.com https://api.aimlapi.com https://cdn.aimlapi.com https://stefna.netlify.app https://ingesteer.services-prod.nsvcs.net; script-src 'self'; style-src 'self' 'unsafe-inline'; frame-src 'self';"