
[build]
  command = "bash scripts/build-for-netlify.sh"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.19.4"
  NPM_FLAGS = "--prefer-offline --no-audit --force"
  VITE_BUILD_OPTIMIZE = "true"

  

# Production context
[context.production]
  command = "bash scripts/build-for-netlify.sh"
  environment = { NODE_ENV = "production" }

# Deploy preview context  
[context.deploy-preview]
  command = "bash scripts/build-for-netlify.sh"
  environment = { NODE_ENV = "preview" }

# Branch deploy context
[context.branch-deploy]
  command = "bash scripts/build-for-netlify.sh"
  environment = { NODE_ENV = "preview" }

# Function optimization
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[functions."unified-generate-background"]
  timeout = 720
  memory = 1536


  # Keep native / build-time-only deps out of the bundle:
  external_node_modules = [
    "@tensorflow/tfjs-node",
    "@mapbox/node-pre-gyp", 
    "mock-aws-s3",
    "aws-sdk",
    "nock"
  ]

# Function-specific configurations
[functions."aimlApi"]
  timeout = 26   # Netlify max for normal functions
  memory = 1024

# Scheduled functions
[functions."reset-daily-credits"]
  schedule = "0 0 * * *"  # Daily at midnight UTC

# Function dependencies are handled by top-level package.json

# Cache optimization
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Content Security Policy for dev server
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com; img-src 'self' data: https: blob:; font-src 'self' data:; connect-src 'self' https: https://www.google-analytics.com https://analytics.google.com; frame-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self';"