// ---- Canonical 25 Presets (exact snake_case IDs) ----
export const PRESETS = {
    cinematic_glow: {
        id: 'cinematic_glow',
        label: 'Cinematic Glow',
        prompt: 'cinematic color grading, warm highlights, deep shadows, rich blacks, subtle teal-orange',
        negative_prompt: 'flat, dull, oversaturated, harsh lighting',
        strength: 0.75,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    bright_airy: {
        id: 'bright_airy',
        label: 'Bright & Airy',
        prompt: 'bright airy atmosphere, soft highlights, clean whites, fresh and light feeling',
        negative_prompt: 'dark, heavy, moody, dramatic shadows',
        strength: 0.65,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    vivid_pop: {
        id: 'vivid_pop',
        label: 'Vivid Pop',
        prompt: 'vibrant colors, enhanced saturation, punchy contrast, bold and energetic look',
        negative_prompt: 'muted, desaturated, flat colors',
        strength: 0.8,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    vintage_film_35mm: {
        id: 'vintage_film_35mm',
        label: 'Vintage Film 35mm',
        prompt: 'vintage 35mm film aesthetic, warm color grading, subtle grain, soft contrast',
        negative_prompt: 'digital, sharp, modern, clinical',
        strength: 0.75,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    tropical_boost: {
        id: 'tropical_boost',
        label: 'Tropical Boost',
        prompt: 'tropical paradise vibes, vibrant greens and blues, warm sunny atmosphere',
        negative_prompt: 'cold, winter, muted colors, urban',
        strength: 0.7,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    urban_grit: {
        id: 'urban_grit',
        label: 'Urban Grit',
        prompt: 'urban street photography, gritty contrast, raw city aesthetic',
        negative_prompt: 'clean, polished, suburban',
        strength: 0.8,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    mono_drama: {
        id: 'mono_drama',
        label: 'Mono Drama (Black & White)',
        prompt: 'dramatic black and white, high contrast, deep shadows, striking monochrome',
        negative_prompt: 'color, colorful, bright, washed out',
        strength: 0.75,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    dreamy_pastels: {
        id: 'dreamy_pastels',
        label: 'Dreamy Pastels',
        prompt: 'soft pastel colors, dreamy atmosphere, gentle lighting, ethereal mood',
        negative_prompt: 'harsh, bold, saturated, dramatic',
        strength: 0.7,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    golden_hour_magic: {
        id: 'golden_hour_magic',
        label: 'Golden Hour Magic',
        prompt: 'magical golden hour light, warm glow, soft shadows, romantic atmosphere',
        negative_prompt: 'harsh midday, artificial lighting',
        strength: 0.75,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    emotion_mask: {
        id: 'emotion_mask',
        label: 'Emotion Mask',
        prompt: 'dual-tone emotional lighting, one side warm soft light and the other cool harsh shadow, sharp eyes, expressive emotion layering, cinematic background blur, conflicting emotional tones',
        negative_prompt: 'flat lighting, single emotion, uniform tone, simple background',
        strength: 0.85,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    high_fashion_editorial: {
        id: 'high_fashion_editorial',
        label: 'High Fashion Editorial',
        prompt: 'high fashion editorial style, dramatic lighting, sophisticated composition, luxury aesthetic',
        negative_prompt: 'casual, amateur, poor lighting, cluttered',
        strength: 0.7,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    moody_forest: {
        id: 'moody_forest',
        label: 'Moody Forest',
        prompt: 'moody forest atmosphere, deep greens, mysterious lighting, natural drama',
        negative_prompt: 'bright, urban, artificial',
        strength: 0.75,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    desert_glow: {
        id: 'desert_glow',
        label: 'Desert Glow',
        prompt: 'warm desert light, golden sand tones, dry heat atmosphere, southwestern vibes',
        negative_prompt: 'cold, wet, lush, tropical',
        strength: 0.7,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    retro_polaroid: {
        id: 'retro_polaroid',
        label: 'Retro Polaroid',
        prompt: 'vintage polaroid aesthetic, soft focus, warm tones, slight vignette',
        negative_prompt: 'sharp, digital, modern',
        strength: 0.7,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    crystal_clear: {
        id: 'crystal_clear',
        label: 'Crystal Clear',
        prompt: 'enhance clarity and sharpness, crisp details, clean and precise look',
        negative_prompt: 'blurry, soft, hazy',
        strength: 0.6,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    ocean_breeze: {
        id: 'ocean_breeze',
        label: 'Ocean Breeze',
        prompt: 'coastal atmosphere, fresh ocean air, cool blue tones, seaside serenity',
        negative_prompt: 'desert, dry, warm tones, inland',
        strength: 0.65,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    festival_vibes: {
        id: 'festival_vibes',
        label: 'Festival Vibes',
        prompt: 'music festival energy, colorful lights, party atmosphere, celebratory mood',
        negative_prompt: 'quiet, subdued, formal, corporate',
        strength: 0.75,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    noir_classic: {
        id: 'noir_classic',
        label: 'Noir Classic',
        prompt: 'film noir aesthetic, dramatic shadows, high contrast black and white',
        negative_prompt: 'bright, colorful, flat lighting',
        strength: 0.75,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    sun_kissed: {
        id: 'sun_kissed',
        label: 'Sun-Kissed',
        prompt: 'warm golden sunlight, natural glow, soft highlights, summer feeling',
        negative_prompt: 'cold, harsh, artificial lighting',
        strength: 0.7,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    frost_light: {
        id: 'frost_light',
        label: 'Frost & Light',
        prompt: 'cool winter light, crisp atmosphere, subtle blue tones, fresh feeling',
        negative_prompt: 'warm, tropical, summer',
        strength: 0.7,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    neon_nights: {
        id: 'neon_nights',
        label: 'Neon Nights',
        prompt: 'cyberpunk neon aesthetic, electric colors, urban nightlife, glowing highlights',
        negative_prompt: 'natural, muted, daylight',
        strength: 0.8,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    cultural_glow: {
        id: 'cultural_glow',
        label: 'Cultural Glow',
        prompt: 'rich cultural atmosphere, warm traditional lighting, heritage aesthetic',
        negative_prompt: 'modern, sterile, cold, commercial',
        strength: 0.7,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    soft_skin_portrait: {
        id: 'soft_skin_portrait',
        label: 'Soft Skin Portrait',
        prompt: 'soft portrait lighting, smooth skin tones, gentle highlights, flattering glow',
        negative_prompt: 'harsh shadows, rough texture, unflattering light',
        strength: 0.6,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    rainy_day_mood: {
        id: 'rainy_day_mood',
        label: 'Rainy Day Mood',
        prompt: 'moody rainy atmosphere, soft gray tones, contemplative feeling, wet reflections',
        negative_prompt: 'sunny, bright, cheerful, dry',
        strength: 0.7,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    wildlife_focus: {
        id: 'wildlife_focus',
        label: 'Wildlife Focus',
        prompt: 'natural wildlife photography, sharp focus, natural habitat, authentic nature',
        negative_prompt: 'artificial, urban, staged, domestic',
        strength: 0.65,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
    street_story: {
        id: 'street_story',
        label: 'Street Story',
        prompt: 'high contrast, rich shadows, enhanced textures for documentary-style street photography',
        negative_prompt: 'posed, studio, artificial, staged',
        strength: 0.7,
        model: 'eagle',
        mode: 'i2i',
        input: 'image',
        requiresSource: true,
    },
};
// Freeze data to prevent runtime mutations
Object.freeze(PRESETS);
// 1) Source of truth for the weekly rotation (exactly 6 ids, rotated weekly)
export const ACTIVE_PRESET_IDS = [
    'crystal_clear',
    'cinematic_glow',
    'neon_nights',
    'vintage_film_35mm',
    'dreamy_pastels',
    'vivid_pop'
];
// Simple preset option mappings
export const OPTION_GROUPS = {
    presets: {}
};
// Freeze option groups to prevent runtime mutations
Object.freeze(OPTION_GROUPS);
// ---- Deep merge (handles nested `post`) ------------------------------------
function mergePreset(base, overrides = {}) {
    return {
        ...base,
        ...overrides,
        post: { ...(base.post ?? {}), ...(overrides.post ?? {}) },
    };
}
// ---- Resolvers & click handlers -------------------------------------------
export function resolvePreset(id, overrides = {}) {
    const base = PRESETS[id];
    if (!base)
        throw new Error(`Preset ${String(id)} missing`);
    return mergePreset(base, overrides);
}
// ---- Safe helpers for UI (no-noop rendering) -------------------------------
export function getOptionEntries(group) {
    const g = OPTION_GROUPS[group] ?? {};
    return Object.entries(g);
}
export function isConfigured(group, key) {
    return Boolean(OPTION_GROUPS[group]?.[key]);
}
