import React from 'react'
import { ArrowLeft } from 'lucide-react'
import { useNavigate } from 'react-router-dom'

const PrivacyPolicy: React.FC = () => {
  const navigate = useNavigate()

  return (
    <div className="min-h-screen bg-black text-white">
      {/* Header */}
      <div className="fixed top-0 left-0 right-0 bg-black/95 backdrop-blur-md border-b border-white/10 z-40">
        <div className="flex items-center justify-between p-4">
          <button
            onClick={() => navigate(-1)}
            className="flex items-center space-x-2 text-white hover:text-white/80 transition-colors"
          >
            <ArrowLeft size={20} />
            <span>Back</span>
          </button>
          <h1 className="text-lg font-semibold">Privacy Policy</h1>
          <div className="w-20"></div> {/* Spacer for centering */}
        </div>
      </div>

      {/* Content */}
      <div className="pt-20 px-6 pb-20 max-w-4xl mx-auto">
        <div className="prose prose-invert max-w-none">
          <h1 className="text-3xl font-bold mb-8">Privacy Policy</h1>
          
          <div className="space-y-6 text-white/90">
            <section>
              <h2 className="text-xl font-semibold mb-4">Interpretation and Definitions</h2>
              <p className="mb-4">
                The words of which the initial letter is capitalized have meanings defined under the following conditions. 
                The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
              </p>
              
              <h3 className="text-lg font-medium mb-3">Definitions</h3>
              <ul className="list-disc pl-6 space-y-2 text-sm">
                <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                <li><strong>Platform</strong> (referred to as either "the Platform", "We", "Us" or "Our" in this Agreement) refers to Stefna.</li>
                <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                <li><strong>Service</strong> refers to the Website, Stefna, an AI-powered photo and video editing platform.</li>
                <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Platform.</li>
                <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                <li><strong>Website</strong> refers to Stefna, accessible from stefna.xyz</li>
                <li><strong>You</strong> means the individual accessing or using the Service, or the Platform, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-4">Collecting and Using Your Personal Data</h2>
              
              <h3 className="text-lg font-medium mb-3">Types of Data Collected</h3>
              
              <h4 className="text-md font-medium mb-2">Personal Data</h4>
              <p className="mb-4">
                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Uploaded Content: Photos and videos uploaded by users, as well as all AI-generated images/videos</li>
                <li>Usage Data</li>
              </ul>

              <h4 className="text-md font-medium mb-2 mt-6">Usage Data</h4>
              <p className="mb-4">
                Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-4">Tracking Technologies and Cookies</h2>
              <p className="mb-4">
                We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. The technologies We use may include:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.</li>
                <li><strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Platform to count users who have visited those pages or opened an email.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-4">Use of Your Personal Data</h2>
              <p className="mb-4">The Platform may use Personal Data for the following purposes:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>To provide and maintain our Service, including to monitor the usage of our Service. This includes storing uploaded content (photos, videos, and AI-generated images/videos) to provide access for the user and enable features like editing and remixing.</li>
                <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
                <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication regarding updates or informative communications related to the functionalities, products or contracted services.</li>
                <li>To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
                <li>To manage Your requests: To attend and manage Your requests to Us.</li>
                <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
                <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
              </ul>
              <p className="mt-4">
                All data is used solely for providing, securing, and improving Stefna's services. We do not sell user data to third parties.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-4">Retention of Your Personal Data</h2>
              <p>
                The Platform will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-4">Transfer of Your Personal Data</h2>
              <p>
                Your information, including Personal Data, is processed at the Platform's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-4">Delete Your Personal Data</h2>
              <p className="mb-4">
                You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Our Service may give You the ability to delete certain information about You from within the Service.
              </p>
              <p>
                You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-4">Security of Your Personal Data</h2>
              <p>
                The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security. All user content and personal information are stored securely using Supabase's managed infrastructure.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-4">Children's Privacy</h2>
              <p>
                You must be at least 13 years old to create an account and use Stefna. If you are under the age required by the laws of your country to consent to data processing (e.g., 16 in some jurisdictions), you may only use Stefna with parental consent. If We become aware that We have collected Personal Data from anyone under the age required by the laws of their country to consent to data processing without verification of parental consent, We take steps to remove that information from Our servers.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-4">Contact Us</h2>
              <p>
                If you have any questions about this Privacy Policy, You can contact us:
              </p>
              <ul className="list-disc pl-6 mt-2">
                <li>By email: <a href="mailto:hello@stefna.xyz" className="text-blue-400 hover:text-blue-300">hello@stefna.xyz</a></li>
              </ul>
            </section>

            <div className="mt-8 pt-6 border-t border-white/20">
              <p className="text-sm text-white/60">
                Last updated: August 4, 2025
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default PrivacyPolicy 